version: 2.1
commands:  
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  hello:
    docker:
      - image: amazon/aws-cli
    steps:      
      - run: echo "hello"

  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout      
      - run:
          name: create and deploy front end
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name bucket-${CIRCLE_WORKFLOW_ID:0:7} \
            --parameter-overrides NAME=bucket-${CIRCLE_WORKFLOW_ID:0:7}
      - run: aws s3 sync s3://udacity-pipeline s3://bucket-${CIRCLE_WORKFLOW_ID:0:7} --delete
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create infrastructure
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name prod-${CIRCLE_WORKFLOW_ID}
      - run: return 1
      - run: 
          name: on fail destroy infra
          command: aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
          when: on_fail
  
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: echo "bucket-${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: create infrastructure
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="bucket-${CIRCLE_WORKFLOW_ID:0:7}" \
            --tags project=udapeople
  save-pipeline-id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: |
            yum install tar -y
            yum install gzip -y
      - run:
          name: save pipeline id
          command:  |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text >> ~/output.txt
            cat ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt    
  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: |
            yum install tar -y
            yum install gzip -y
      - attach_workspace:
          at: ~/output.txt
      - run: |
          aws s3 rm "s3://bucket-${CIRCLE_WORKFLOW_ID:0:7}" --force
          aws cloudformation delete-stack --stack-name "bucket-${CIRCLE_WORKFLOW_ID:0:7}"

  cloudfront-distro:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create infrastructure
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID=udacity-pipeline \
            --tags project=udapeople      
      

workflows:
  my_workflow:
    jobs:
      - create_and_deploy_front_end
      - save-pipeline-id:
          requires:
            - create_and_deploy_front_end
      - promote_to_production:
          requires:
            - save-pipeline-id
      - clean_up_old_front_end:
          requires:
            - promote_to_production
        
                          
          
        