version: 2.1
commands:  
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  hello:
    docker:
      - image: amazon/aws-cli
    steps:      
      - run: echo "hello"

  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create and deploy front end
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name bucket-${CIRCLE_WORKFLOW_ID:0:5} \
            --parameter-overrides NAME="${CIRCLE_WORKFLOW_ID:0:5}"
      - run: aws s3 sync . s3://"${CIRCLE_WORKFLOW_ID:0:5}" --delete
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create infrastructure
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name prod-${CIRCLE_WORKFLOW_ID}
      - run: return 1
      - run: 
          name: on fail destroy infra
          command: aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
          when: on_fail
  
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create infrastructure
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}" \
            --tags project=udapeople
  cloudfront-distro:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create infrastructure
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID=udacity-pipeline \
            --tags project=udapeople      
      

workflows:
  my_workflow:
    jobs:
      - create_and_deploy_front_end
      - promote_to_production:
          requires: 
            - create_and_deploy_front_end
        
                          
          
        