version: 2.1
jobs:
  config_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e9:1e:77:667"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Ensure backend infrastructure exist
          command: |
            ansible-playbook -i inventory.txt main-remote.yml
workflows:
  my_workflow:
    jobs:
      - config_infrastructure
