version: 2.1
commands:  
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name prod-${CIRCLE_WORKFLOW_ID}
  destroy_stack:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Simulate Error
          command: |
            return 1
      - destroy_environment
      

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      - destroy_stack:
          requires:
            - create_infrastructure    
        