version: 2.1
commands:  
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  hello:
    docker:
      - image: amazon/aws-cli
    steps:      
      - run: echo "hello"

  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create and deploy front end
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name "${CIRCLE_WORKFLOW_ID:0:7}" \ # ${CIRCLE_WORKFLOW_ID:0:7} takes the first 7 chars of the variable CIRCLE_CI_WORKFLOW_ID
            --parameter-overrides NAME="${CIRCLE_WORKFLOW_ID:0:7}"
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create infrastructure
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name prod-${CIRCLE_WORKFLOW_ID}
      - run: return 1
      - run: 
          name: on fail destroy infra
          command: aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
          when: on_fail

  cloudfront-distro:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create infrastructure
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID=udacity-pipeline \
            --tags project=udapeople      
      

workflows:
  my_workflow:
    jobs:
      - create_and_deploy_front_end
          
        